openapi: 3.0.3
info:
  title: Task API (bundled)
  version: 1.0.0
  description: Bundled API for Swagger UI
servers:
  - url: /
paths:
  /tasks:
    get:
      summary: Get list of tasks
      responses:
        '200':
          description: A list of tasks
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Task'
    post:
      summary: Create a task
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TaskInput'
      responses:
        '201':
          description: Created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Task'

  /tasks/{id}:
    get:
      summary: Get a task by ID
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Task found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Task'
        '400':
          description: Validation failed
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ValidationError'
        '404':
          description: Not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/NotFoundError'

components:
  schemas:
    Task:
      type: object
      properties:
        id:
          type: integer
        title:
          type: string
        completed:
          type: boolean
      required:
        - id
        - title
        - completed

    TaskInput:
      type: object
      properties:
        title:
          type: string
        completed:
          type: boolean
      required:
        - title

    ValidationError:
      type: object
      properties:
        error:
          type: string
        details:
          type: array
          items:
            type: string

    NotFoundError:
      type: object
      properties:
        error:
          type: string
      example:
        error: "Task not found"
